message = "go to pku"
print(message)
message = "go to thu"
print(message)
first_name = "joe"
last_name = "biden"
full_name = f"{first_name} {last_name}"
print(full_name)
print(f"hello, {full_name}")
print(f"{first_name} {last_name}")
print(f"hello,{full_name.title()}")
print(f"hello,full_name")
# print(f"hell0, {f"{first_name} {last_name}"}") -->运行不了，错误的写法
print("\tgo\n to ccnu")
guests = ['yjm', 'fcc', 'lym', 'zxr', 'hlw']
print(guests)
print('lym can not come')
print(f"{guests[1]} can not come")
leave_guest = guests.pop(1)
guests.insert(1, 'why')
print(guests)
guests.append('sky')
print(guests)
print('find a bigger table')
guests.insert(0, 'yx')
guests.insert(3, 'sh')
guests.append('sj')
print(guests)
print(f"{guests[0].title()} welcome to my party")
print("only come 2 guests")
sorry_guest = guests.pop()
print(f"{sorry_guest},i am so sorry to do that")
sorry_guest = guests.pop()
print(f"{sorry_guest},i am so sorry to do that")
sorry_guest = guests.pop()
print(f"{sorry_guest},i am so sorry to do that")
sorry_guest = guests.pop()
print(f"{sorry_guest},i am so sorry to do that")
sorry_guest = guests.pop()
print(f"{sorry_guest},i am so sorry to do that")
sorry_guest = guests.pop()
print(f"{sorry_guest},i am so sorry to do that")
print(guests)
del guests[0]
print(*guests)
print(len(guests))
del guests[-1]
print(*guests)

places = ['NewYork', 'LonDon', 'Paris', 'Shanghai', 'Sanya']
print(places)
print(sorted(places))
print(places)
print(sorted(places, reverse=True))
print(places)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort(reverse=True)
print(places)

everything = []
everything.append('huangshan')
everything.append('changjiang')
everything.append('America')
print(everything)
print(sorted(everything))
everything.insert(1, 'Beijing')
print(everything)
print(sorted(everything))
print(sorted(everything,reverse=True))
print(everything)
print(len(everything))
everything.sort()
print(everything)
everything.sort(reverse=True)
print(everything)
everything.reverse()
print(everything)
everything.reverse()
print(everything)
pop_everything = everything.pop()
print(f"{pop_everything} is happy")
print(everything)
pop_everything2 = everything.pop(0)
print(f"{pop_everything2} is happy")
print(f"{pop_everything} is happy")
print(everything)
remove_everything='changjiang'
everything.remove(remove_everything)
print(*everything)
print(f'{remove_everything} is bad')
del everything[0]
print(everything)

